<?php

/**
 * @file
 * Install functions for DruxtJS.
 */

declare(strict_types=1);

use Drupal\Component\Utility\DeprecationHelper;
use Drupal\Core\Extension\Requirement\RequirementSeverity;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_install().
 */
function druxt_install(): void {
  druxt_ensure_entity_view_displays();
}

/**
 * Implements hook_requirements().
 */
function druxt_requirements(string $phase): array {
  $requirements = [];

  if (\Drupal::hasService('jsonapi.resource_type.repository')) {
    $module_handler = \Drupal::service('module_handler');
    $resource_type_repository = \Drupal::service('jsonapi.resource_type.repository');

    $required_resources = [
      'block--block',
      'entity_form_display--entity_form_display',
      'entity_form_mode--entity_form_mode',
      'entity_view_display--entity_view_display',
      'entity_view_mode--entity_view_mode',
      'field_config--field_config',
      'field_storage_config--field_storage_config',
      'menu--menu',
      'menu_link_content--menu_link_content',
      'view--view',
    ];
    $disabled_resources = [];
    $missing_resources = [];
    foreach ($required_resources as $resource) {
      [$entity, $bundle] = explode('--', $resource);
      $resource_type = $resource_type_repository->get($entity, $bundle);
      if (!$resource_type) {
        $missing_resources[] = $resource;
        continue;
      }
      if ($resource_type->isInternal() == TRUE) {
        if ($module_handler->moduleExists('jsonapi_extras')) {
          $disabled_resources[] = new Link(
            $resource,
            Url::fromRoute('entity.jsonapi_resource_config.edit_form', ['jsonapi_resource_config' => $resource], [
              'query' => ['destination' => Url::fromRoute('system.status')->toString()],
            ])
          );
        }
        else {
          $disabled_resources[] = $resource;
        }
      }
    }

    // Report missing resources.
    if (count($missing_resources)) {
      if ($phase === 'install') {
        \Drupal::messenger()->addWarning(t('Some required JSON:API resources are missing which may prevent a Druxt frontend from operating correctly. See the <a href=":status">Status report</a> for details.', [':status' => Url::fromRoute('system.status')->toString()]));
      }

      $requirements['druxt_resources_missing'] = [
        'title' => t('Druxt JSON:API resources missing'),
        'value' => t('The following JSON:API resources are missing which may prevent a Druxt frontend from operating correctly:'),
        'description' => [
          '#theme' => 'item_list',
          '#items' => $missing_resources,
        ],
        'severity' => DeprecationHelper::backwardsCompatibleCall(\Drupal::VERSION, '11.2.0', fn(): RequirementSeverity => RequirementSeverity::Warning, fn() => REQUIREMENT_WARNING),
      ];
    }

    // Report disabled resources.
    if (count($disabled_resources)) {
      if ($phase === 'install') {
        \Drupal::messenger()->addWarning(t('Some required JSON:API resources are disabled which may prevent a Druxt frontend from operating correctly. See the <a href=":status">Status report</a> for details.', [':status' => Url::fromRoute('system.status')->toString()]));
      }

      $requirements['druxt_resources_disabled'] = [
        'title' => t('Druxt JSON:API resources disabled'),
        'value' => t('The following JSON:API resources are disabled which may prevent a Druxt frontend from operating correctly:'),
        'description' => [
          '#theme' => 'item_list',
          '#items' => $disabled_resources,
        ],
        'severity' => DeprecationHelper::backwardsCompatibleCall(\Drupal::VERSION, '11.2.0', fn(): RequirementSeverity => RequirementSeverity::Warning, fn() => REQUIREMENT_WARNING),
      ];
    }
  }

  return $requirements;
}

/**
 * Fix missing EntityViewDisplays.
 */
function druxt_update_9000(): void {
  druxt_ensure_entity_view_displays();
}
