<?php

use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\jsonapi\Routing\Routes;

define('DRUXT_RESOURCES', [
  'block--block',
  'entity_form_display--entity_form_display',
  'entity_form_mode--entity_form_mode',
  'entity_view_display--entity_view_display',
  'entity_view_mode--entity_view_mode',
  'field_config--field_config',
  'field_storage_config--field_storage_config',
  'menu_link_content--menu_link_content',
  'view--view'
]);

/**
 * Checks for Druxt route access.
 */
function druxt_access_check(AccountInterface $account) {
  $route = \Drupal::routeMatch()->getRouteObject();
  if (!$route) {
    return FALSE;
  }

  $defaults = $route->getDefaults();

  // Is the route a JSON API request?
  if (!Routes::isJsonApiRequest($defaults)) {
    return FALSE;
  }

  // Is the JSON API resource a Druxt resource?
  if (!in_array($defaults['resource_type'], DRUXT_RESOURCES)) {
    return FALSE;
  }

  // Is the route a GET request?
  if (!in_array('GET', $route->getMethods())) {
    return FALSE;
  }

  // Does the user have access?
  if (!$account->hasPermission('access druxt resources')) {
    return FALSE;
  }

  return TRUE;
}

/**
 * Implements hook_entity_access().
 */
function druxt_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  return druxt_access_check($account) ? AccessResult::allowed() : AccessResult::neutral();
}

/**
 * Implements hook_jsonapi_entity_filter_access().
 */
function druxt_jsonapi_entity_filter_access(EntityTypeInterface $entity_type, AccountInterface $account) {
  if (!druxt_access_check($account)) {
    return;
  }

  return ([
    JSONAPI_FILTER_AMONG_ALL => AccessResult::allowed(),
  ]);
}

/**
 * Implments hook_condition_info_alter().
 */
function druxt_condition_info_alter(array &$info) {
  // Use custom 'request_path' plugin to allow setting of the path from Druxt frontend.
  $info['request_path']['class'] = 'Drupal\druxt\Plugin\Condition\DruxtRequestPath';
  $info['request_path']['provider'] = 'druxt';
}
