<?php

/**
 * @file
 * Drupal module hooks and shared functionality.
 */

declare(strict_types=1);

use Drupal\Component\Utility\DeprecationHelper;
use Drupal\jsonapi\JsonApiFilter;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\jsonapi\Routing\Routes;

/**
 * Checks for Druxt route access.
 */
function druxt_access_check(AccountInterface $account) {
  $route = \Drupal::routeMatch()->getRouteObject();
  if (!$route) {
    return FALSE;
  }

  $defaults = $route->getDefaults();

  // Is the route a JSON API request?
  if (!Routes::isJsonApiRequest($defaults)) {
    return FALSE;
  }

  // Is the JSON API resource a Druxt resource?
  $resources = [
    'block--block',
    'configurable_language--configurable_language',
    'entity_form_display--entity_form_display',
    'entity_form_mode--entity_form_mode',
    'entity_view_display--entity_view_display',
    'entity_view_mode--entity_view_mode',
    'field_config--field_config',
    'field_storage_config--field_storage_config',
    'jsonapi_resource_config--jsonapi_resource_config',
    'menu--menu',
    'menu_link_content--menu_link_content',
    'view--view',
  ];
  if (!in_array($defaults['resource_type'], $resources)) {
    return FALSE;
  }

  // Is the route a GET request?
  if (!in_array('GET', $route->getMethods())) {
    return FALSE;
  }
  // Does the user have access?
  return $account->hasPermission('access druxt resources');
}

/**
 * Implements hook_entity_access().
 */
function druxt_entity_access(EntityInterface $entity, string $operation, AccountInterface $account) {
  return druxt_access_check($account) ? AccessResult::allowed() : AccessResult::neutral();
}

/**
 * Implements hook_entity_bundle_create().
 */
function druxt_entity_bundle_create(string $entity_type_id, string $bundle): void {
  if (\Drupal::isConfigSyncing()) {
    return;
  }
  druxt_ensure_entity_view_display($entity_type_id, $bundle);
}

/**
 * Implements hook_jsonapi_entity_filter_access().
 */
function druxt_jsonapi_entity_filter_access(EntityTypeInterface $entity_type, AccountInterface $account): ?array {
  if (!druxt_access_check($account)) {
    return NULL;
  }

  $jsonapi_filter = DeprecationHelper::backwardsCompatibleCall(\Drupal::VERSION, '11.3.0', fn(): string => JsonApiFilter::AMONG_ALL, fn() => JSONAPI_FILTER_AMONG_ALL);
  return [
    $jsonapi_filter => AccessResult::allowed(),
  ];
}

/**
 * Implements hook_condition_info_alter().
 */
function druxt_condition_info_alter(array &$info): void {
  // Use custom 'request_path' plugin to allow setting of the path from DruxtJS
  // frontend.
  $info['request_path']['class'] = 'Drupal\druxt\Plugin\Condition\DruxtRequestPath';
  $info['request_path']['provider'] = 'druxt';
}

/**
 * Ensure that all required EntityViewDisplays are available.
 */
function druxt_ensure_entity_view_displays(): void {
  $bundle_info = \Drupal::service('entity_type.bundle.info');
  $display_repository = \Drupal::service('entity_display.repository');

  $view_modes = $display_repository->getAllViewModes();
  $definitions = \Drupal::entityTypeManager()->getDefinitions();

  foreach (array_keys($view_modes) as $entity_type_id) {
    if (!in_array($entity_type_id, array_keys($definitions), TRUE)) {
      continue;
    }

    $class = $definitions[$entity_type_id]->getClass();
    if ($class === NULL || !is_subclass_of($class, FieldableEntityInterface::class, TRUE)) {
      continue;
    }

    $bundles = $bundle_info->getBundleInfo($entity_type_id);
    foreach (array_keys($bundles) as $bundle) {
      $displays = $display_repository->getViewModeOptionsByBundle($entity_type_id, $bundle);
      if (empty($displays)) {
        $displays = ['default' => TRUE];
      }
      foreach (array_keys($displays) as $mode) {
        druxt_ensure_entity_view_display($entity_type_id, $bundle, $mode);
      }
    }
  }
}

/**
 * Ensure that a specified EntityViewDisplay is present, or create it.
 */
function druxt_ensure_entity_view_display(string $entity_type_id, string $bundle, string $mode = 'default'): void {
  $result = \Drupal::entityQuery('entity_view_display')
    ->accessCheck(TRUE)
    ->condition('id', sprintf('%s.%s.%s', $entity_type_id, $bundle, $mode))
    ->execute();
  if (empty($result)) {
    // Create missing configuration entities.
    EntityViewDisplay::create([
      'targetEntityType' => $entity_type_id,
      'bundle' => $bundle,
      'mode' => $mode,
      'status' => TRUE,
    ])->save();
  }
}
